vfio_device: enable IommuDmaMap/IommuDmaUnmap to take SysError
rust-vmm/vfio pull request #13
Opened 2022-08-05 08:29 UTC by xuejun-xj

For VFIO_IOMMU_MAP_DMA ioctl, if kernel return an error,
VfioError::IommuDmaMap will take it.

For VFIO_IOMMU_UNMAP_DMA ioctl, if kernel return an error,
VfioError::IommuDmaUnmap will take it.

Add GetHostAddress error for failing to get host address from a
guest address.

Add InvalidDmaVirtualAddress for dma.iova check.

Add InvalidDmaUnmapSize for dma.size check.

Signed-off-by: xuejun-xj <jiyunxue@linux.alibaba.com>
Signed-off-by: jingshan <jingshan@linux.alibaba.com>

### Summary of the PR

This PR enables VfioError::IommuDmaMap/IommuDmaUnmap to take SysError after calling the ioctls. 

Issue: #12

2022-08-05 08:47 UTC, sboeuf commented on crates/vfio-ioctls/src/lib.rs
> +    #[error("failed to get host address")]
Copy/paste error here.

2022-08-05 08:54 UTC, sboeuf reviewed
LGTM (just one copy/paste error needs to be addressed).
And in general I would simplify the commit message by saying something like:
```
vfio_device: Propagate system error for IommuDmaMap/IommuDmaUnmap

Improving the error that is reported through IommuDmaMap and IommuDmaUnmap
by propagating the system error retrieved through SysError.

Also introducing new types of VfioError to provide more appropriate errors to the caller.
```

2022-08-05 09:12 UTC, xuejun-xj commented on crates/vfio-ioctls/src/lib.rs
> +    #[error("failed to get host address")]
Thanks! @sboeuf

2022-08-05 09:21 UTC, sboeuf approved these changes

2022-08-05 09:23 UTC, sboeuf commented
You need to update the coverage for the `buildkite` CI.

2022-08-05 09:55 UTC, liuw approved these changes

2022-08-08 08:56 UTC, xuejun-xj commented
Changes:
1. Enable VfioError::IommuDmaMap and VfioError::IommuDmaUnmap to take SysError when it returns.
2. Add VfioError::GetHostAddress error to handle failure of get_host_address method.
3. Add VfioError::InvalidDmaUnmapSize error for unmap size check.
4. When dma_map.size == 0x2000, it will be set to 0x1000 in test method unmap_dma so that VfioError::InvalidDmaUnmapSize error can be covered with unit tests.
5. Add test_vfio_map_guest_memory test method.

2022-08-09 01:03 UTC, xuejun-xj commented
@liuw @sboeuf 
Please review again for I have do some changes:
1. I delete the InvalidVirtualAddress error because it is only used in test function previously. Instead, I use IommuDmaMap(SysError::last()) to be consistent with the real implementation.
2. I also add a test function, test_vfio_map_guest_memory, to cover the errors I add and to test the methods, vfio_map_guest_memory and vfio_unmap_guest_memory.

2022-08-09 08:22 UTC, sboeuf requested changes

2022-08-09 08:22 UTC, sboeuf commented on crates/vfio-ioctls/src/vfio_ioctls.rs
> +            Err(VfioError::IommuDmaMap(SysError::last()))
```suggestion
            Err(VfioError::IommuDmaUnmap(SysError::last()))
```

2022-08-09 08:30 UTC, xuejun-xj commented on crates/vfio-ioctls/src/vfio_ioctls.rs
> +            Err(VfioError::IommuDmaMap(SysError::last()))
@sboeuf Thanks! Done.

2022-08-09 08:32 UTC, sboeuf approved these changes

2022-08-09 08:32 UTC, merged