ioctls: reenable support of mshv
rust-vmm/vfio pull request #3
Opened 2021-12-20 13:32 UTC by jiangliu

The vfio-ioctls v0.1.0 has been published, so reenable support of mshv.

Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>

2021-12-20 16:52 UTC, liuw commented
Changes look good. I think you missed bumping the version number.

In any case, this will need to wait until we publish mshv crates to crates.io.

2021-12-21 02:51 UTC, jiangliu commented
> Changes look good. I think you missed bumping the version number.
> 
> In any case, this will need to wait until we publish mshv crates to crates.io.

The version number will be bumped when publishing next version:)

2021-12-21 07:21 UTC, sboeuf approved these changes

2021-12-21 16:03 UTC, andreeaflorescu requested changes
Can we first discuss about publishing mshv? I have some concerns regarding this. It seems like the publishing of the mshv-* crates is rushed because of vfio-ioctls (for example, the coverage of the crate is now ~25% which is very low compared to all the other crates published in crates.io).

The initial plan as I understood from other comments was to publish mshv in January. Can we wait with the update until then? More comments on this topic here: https://github.com/rust-vmm/mshv/pull/25#discussion_r773256507

2021-12-22 00:58 UTC, jiangliu commented
> Can we first discuss about publishing mshv? I have some concerns regarding this. It seems like the publishing of the mshv-* crates is rushed because of vfio-ioctls (for example, the coverage of the crate is now ~25% which is very low compared to all the other crates published in crates.io).
> 
> The initial plan as I understood from other comments was to publish mshv in January. Can we wait with the update until then? More comments on this topic here: [rust-vmm/mshv#25 (comment)](https://github.com/rust-vmm/mshv/pull/25#discussion_r773256507)

We have already published vfio-ioctls v0.1 without support of mshv, and there's no plan for v0.2 yet.
So no rush for mshv anymore. We could publish v0.2 for mshv according to mshv's plan.

2021-12-22 00:59 UTC, jiangliu commented
This is just to reenable vfio-ioctls for mshv, so that Cloud hypervisor may consume the main branch.

2022-02-04 10:50 UTC, sboeuf commented
@liuw @rbradford that's a bit problematic that we don't have the `mshv` support anymore because Cloud Hypervisor can't move from the now deprecated `rust-vmm/vfio-ioctls` crate to `rust-vmm/vfio`.
I can only see two options here, either we disable the need for `mshv` from Cloud Hypervisor, or we push for the `mshv` support to be merged in `rust-vmm/vfio` (effectively pushing for this PR to be merged).

2022-02-04 10:53 UTC, jiangliu commented
I feel the solution is to merge this PR first to unblock Cloud Hypervisor.
Then move on to publish the mshv crate.

2022-02-04 10:54 UTC, merged

2022-02-04 12:15 UTC, liuw commented
Thanks @jiangliu . @sboeuf let me know if anything else is needed.

2022-02-04 12:57 UTC, sboeuf commented
No everything's good!